### ISSUE TITLE
Configuration testing 

### ISSUE THREAD

**Issue by ojab** [karafka/karafka-testing#113]
We're checking if karafka configuration is properly filled in specs, because we're getting all the configuration via
```ruby
ENV['something'] = 'foo' # dotenv
MyApp.config.something = ENV['something'] # dry-c w/ contract
KarafkaApp.config.something = MyApp.config.something
```
and it's good to test if seed brokers etc is properly propagated.

With karafka-1 it was (simplified):
`karafka.rb`:
```ruby
require 'my_app/karafka_app'

MyApp::KarafkaApp.boot!
```
`my_app/karafka_app.rb`
```ruby
module MyApp
  # Main MyApp karafka consumer application. Starting via `<APP_ROOT>/karafka.rb`.
  class KarafkaApp < Karafka::App
    class << self
      # Setup application. This method allow us to re-run setup (e.g. for testing purposes)
      def boot!
        setup do |config|
          config.something = MyApp.config.something
        end

        draw_routes

        super

        setup_waterdrop

        config.finalize!
      end
  end
end
```

`spec/my_app/karafka_app_spec.rb`
```ruby
RSpec.describe MyApp::KarafkaApp do
  def setup_karafka_app
    allow(Karafka::Setup::Config).to receive(:config).and_return(described_class.config.pristine)
    allow(WaterDrop::Config).to receive(:config).and_return(WaterDrop.config.pristine)
    allow(DeliveryBoy).to receive(:config).and_return(DeliveryBoy::Config.new(env: ENV))

    described_class.boot!
  end

  it { expect { setup_karafka_app }.to get_config(:something).from_envvar(:something) }
end
```
and now setup is approx. the same, but it's not clear what should be used instead of `#pristine` to get a copy of the config in these specs:
```
(ruby) described_class.config.concurrency
5
(ruby) described_class.config.deep_dup.concurrency
eval error: undefined method `concurrency' for #<Karafka::Core::Configurable::Node:0x00007f0ea0fe8f48 @name=:root,…

described_class.config.deep_dup.concurrency
                               ^^^^^^^^^^^^
```

So some method to get a config that could be messed with is needed.

**Comment by mensfeld** [comment]
Can you expand this for me?

> it { expect { setup_karafka_app }.to get_config(:something).from_envvar(:something) }

That is, how would this exact spec look in vanilla rspec? Like so?

```ruby
it { expect(setup_karafka_app.something).to eq(ENV['SOMETHING']) }
```

**Comment by ojab** [comment]
There is a custom matcher, but essentially yes, it's something like
```ruby
allow(ENV).to receive('FOO').and_return('bar')
expect(setup_karafka_app.something).to eq('bar')

allow(ENV).to receive('FOO').and_return('baz')
expect(setup_karafka_app.something).to eq('baz')
```
with extra steps under the hood.

**Comment by mensfeld** [comment]
@ojab can't you check the assigned target values like so?

```ruby
it { expect(KarafkaApp.config.kafka[:'bootstrap.servers']).to eq('blabla') }
```

**Comment by ojab** [comment]
Sure, we're doing the same thing since `setup_karafka_app` returns `KarafkaApp.config`. But I don't see how this could help us to prevent config pollution.

**Comment by mensfeld** [comment]
@ojab ok so instead of checking the values you actually want to make sure they come from a legit/expected source. Ok makes sense.

**Comment by ojab** [comment]
Yep,
1. Testing values shouldn't pollute current/global `Karafka.config
2. Current config shouldn't affect testing values (ideally)
So we need some common ground to compare testing results with. In karafka-1.4 it was a pristine config, in karafka-2.0 it could be current config, but it should be immutable during/after the tests.

**Comment by mensfeld** [comment]
I don't think this will be achievable easily with the auto-design now but I will try to think about it.

**Comment by mensfeld** [comment]
I thought about it. I don't know how to do it :( anything I would come up with would be a traidoff of convenience vs flexibility.

**Comment by mensfeld** [comment]
I did not came with anything that would satisfy your needs. If you have a idea that would not break the current API, happy to get back to this.
