### ISSUE TITLE
NameError: uninitialized constant WaterDrop::Producer::DummyClient

### ISSUE THREAD

**Issue by jordanfbrown** [karafka/karafka-testing#145]
I'm seeing the following error after upgrading to 2.1.1:

```
NameError: uninitialized constant WaterDrop::Producer::DummyClient

    class SpecProducerClient < ::WaterDrop::Producer::DummyClient
                                                    ^^^^^^^^^^^^^
from /Users/jordan/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/karafka-testing-2.1.1/lib/karafka/testing/spec_producer_client.rb:7:in `<module:Testing>'
```

It looks like `WaterDrop::Producer::DummyClient` was renamed to `WaterDrop::Clients::Dummy` in this PR: https://github.com/karafka/waterdrop/pull/353, but there was no corresponding change in this project to update it.

I see a closed issue here that looks like it may be related, but not 100% sure: https://github.com/karafka/karafka-testing/issues/142

**Comment by mensfeld** [comment]
You pointed that correctly. Not sure why I closed this one instead of finishing the release :facepalm:

**Comment by mensfeld** [comment]
@jordanfbrown it has been fixed with the new release. Sorry.

I always bump waterdrop + re-run all the integrations and example apps but this time I just assumed that this ticket was wrong :shrug: will make sure it won;t happen again.

**Comment by jordanfbrown** [comment]
No worries @mensfeld! Thank you for the quick fix and all your work on Karafka.

**Comment by mensfeld** [comment]
@jordanfbrown anytime.

FYI feel free to join our slack - it's much faster to consult and get info there: https://slack.karafka.io/

also if you find karafka ecosystem useful, please don't forget to :star:  the main repo: https://github.com/karafka/karafka it helps me grow the community :pray:
