### ISSUE TITLE
Support for testing around pattern matching in topic to consumer mapping

### ISSUE THREAD

**Issue by MatthewRDodds** [karafka/karafka-testing#166]
Thank you for this library, it's been very helpful for testing my topic to consumer mappings and making sure the correct consumer class is invoked and the correct behavior is found.

I'm switching now to using patterns instead of named topics, specifically for the DLQ case as described in the [docs](https://karafka.io/docs/Pro-Routing-Patterns/#enabling-routing-patterns).

In my spec I'm using:

```ruby
karafka.consumer_for("dlq-demo-topic")
```

And in my consumer mapping I have:

```ruby
pattern(:dlqs_pattern, /^dlq.*/) do
  consumer DeadLetterQueueConsumer
end
```

I've tried a few different variations of the regex, but I always get `Karafka::Testing::Errors::TopicNotFoundError` when running my tests. As I understand, testing pattern matches like this is not currently supported.

**Comment by mensfeld** [comment]
Indeed, it should be supported.

**Comment by mensfeld** [comment]
@MatthewRDodds would you mind checking if this PR works for you? https://github.com/karafka/karafka-testing/pull/167 it works for me :)
