### ISSUE TITLE
uninitialized constant Karafka::Testing::Errors::ConsumerGroupNotFound 

### ISSUE THREAD

**Issue by ujasur** [karafka/karafka-testing#218]
I am running into `uninitialized constant Karafka::Testing::Errors::ConsumerGroupNotFound` error when requesting unknown consumer.
Does the code have typo at this line - https://github.com/karafka/karafka-testing/blob/v2.4.1/lib/karafka/testing/helpers.rb#L42 and actual error name must be `ConsumerGroupNotFoundError`?

**Comment by mensfeld** [comment]
Fixed in the linked PR. Thank you <3

**Comment by mensfeld** [comment]
released :pray:
