### ISSUE TITLE
Can't get consumer with `consumer_for` when topics are duplicated across subscription groups

### ISSUE THREAD

**Issue by joshuay03** [karafka/karafka-testing#221]
For reasons I won't get into, we need to temporarily have 2 consumers processing all the messages in a single topic independently of each other. With the following setup:

```ruby
subscription_group "group-1" do
  topic "topic-1" do
    consumer Consumer1
  end
end

subscription_group "group-2" do
  topic "topic-1" do
    consumer Consumer2
  end
end
```

if we use `consumer_for` with a single (topic) arg we get:

```ruby
karafka.consumer_for("topic-1")

#  Karafka::Testing::Errors::TopicInManyConsumerGroupsError:
#    topic-2
```

which makes sense.

If we try with the second (consumer group) arg as well we get:

```ruby
karafka.consumer_for("topic-1", "group-1")

#  Karafka::Testing::Errors::ConsumerGroupNotFoundError:
#    topic-2
```

which I guess makes sense cause it's a subscription group, not a consumer group (although reading the code it seems like the former is mostly a wrapper for the latter).

But, if we use `consumer_group`s instead:

```ruby
consumer_group "group-1" do
  topic "topic-1" do
    consumer Consumer1
  end
end

consumer_group "group-2" do
  topic "topic-1" do
    consumer Consumer2
  end
end
```

 we get:

```ruby
karafka.consumer_for("topic-1", "group-1")

# #<Foundation::Consumer1:0x000000032559cf18
#   ...
```

I guess my question is, is there a way to use this API to get the consumer for a specific group while still using the first setup.

Code where the lookup happens for reference:
https://github.com/karafka/karafka-testing/blob/e07d2b8b4ac9134d14ccf274cfe2864cad315660/lib/karafka/testing/helpers.rb#L35-L53

**Comment by mensfeld** [comment]
this should not even be possible and if it is, it is a bug and I need to fix that:

```
subscription_group "group-1" do
  topic "topic-1" do
    consumer Consumer1
  end
end

subscription_group "group-2" do
  topic "topic-1" do
    consumer Consumer2
  end
end
```

**Comment by mensfeld** [comment]
> (although reading the code it seems like the former is mostly a wrapper for the latter).

not really. those are distinct concepts that have different usage. Investigating...

**Comment by mensfeld** [comment]
Closing. Same topic should not be consumed twice in the same CG. If allowed, it means that there's a routing validation bug.
