### ISSUE TITLE
Testing producer code

### ISSUE THREAD

**Issue by Cameron2920** [karafka/karafka-testing#89]
I want to be able test my code that produces messages. For example, if I have the following method

```
def test_method(val)
  Karafka.producer.produce_async(
      topic: "test",
      payload: {
        val: val
      }.to_json
  )
end
```

I would ideally like to test this by checking an event was added to the "test" topic with an appropriate payload. Is there a way to achieve this with the karafka-testing gem? Or maybe an alternative recommended way to test producer code?

**Comment by mensfeld** [comment]
Aside from stubbing, there is no method.

We could use a new test low-level client like the dummy one: https://github.com/karafka/waterdrop/blob/master/lib/waterdrop/producer/dummy_client.rb and use it with Karafka-Testing to accumulate messages.

I will make it into a card but cannot promise the ETA.

**Comment by Cameron2920** [comment]
Thanks for the reply! 

For now, I'll implement a mock producer that stores events in memory and exposes methods to view the stored events.

If this is something you think would be useful for this gem, I can make a PR when I'm finished.

**Comment by mensfeld** [comment]
It is. It would be good to have a way to buffer this data instead of just ignoring it in test env. Would be happy to see your code and then we can polish it into a feature. Thanks!

**Comment by Cameron2920** [comment]
@mensfeld I've made a PR here https://github.com/karafka/karafka-testing/pull/90. I can make additional updates/add documentation if needed.

**Comment by mensfeld** [comment]
Took me a while (sorry), let me take a look...

**Comment by mensfeld** [comment]
@Cameron2920 I took your code and in the upcoming days (I have a cold so around weekend) will ship your changes alongside mine. `Karafka.producer` messages will now target both consumer and buffer, meaning we can ditch the `karafka.publish` and can just send messages and the once that will target given consumer will reach it.

Thank you for your code.

**Comment by mensfeld** [comment]
Actually both will be available. Will update the docs once ready.
