### ISSUE TITLE
Allow specifying target consumer_group when creating a test consumer with `#karafka_consumer_for`

### ISSUE THREAD

**Issue by mrfarmer777** [karafka/karafka-testing#92]
When multiple consumer groups are configured to consume from the same topic, as in the example below, the `#karafka_consumer_for` method will register its returned consumer only to the consumer group is defined last in the Karafka configuration file. 

### my_app.rb
```ruby
class MyApp < Karafka::App
  consumer_groups.draw do
      consumer_group :group_one do
        topic("incoming_events") { consumer EventProcessingConsumer }
      end
  
      consumer_group :group_two do
        topic("incoming_events") { consumer EventReportingConsumer }
      end
    end
end
```

### event_processing_consumer_spec.rb
```ruby
RSpec.describe EventProcessingConsumer do
  subject(:consumer) { karafka_consumer_for("incoming_events") }

  # consumer is registered to the topic for  consumer group two 
  # since it is the last one defined in the consumer_group.draw block
  consumer.topic.consumer_group # => group_two 
end
```

I think this issue occurs because of the way the method iterates over the available topic names [here](https://github.com/karafka/karafka-testing/blob/635016f6b61641b8729219f63081a842278d44e7/lib/karafka/testing/rspec/helpers.rb#L43), which seems to disregard the consumer_group for which the topic is registered. I would be helpful to be able to optionally pass a target `consumer_group_name` arg to this method in order to ensure the consumer was registered to the correct group/topic combination.

**Comment by mensfeld** [comment]
Yes, you are right and it's worth implementing. Will do.

**Comment by mensfeld** [comment]
@mrfarmer777 would you mind giving it a run? https://github.com/karafka/karafka-testing/pull/93 :) just want to make sure. I did test it out on the example apps, and seems to satisfy all the cases:
- [x] no API changes for anyone that uses it without problems
- [x] raises an exception when the same topic is used in multiple consumer groups but not limited when specified (so no mistakes)
- [x] allows for the specification of the target consumer group
- [x] raises an exception when within a given consumer group topic is not found
