### ISSUE TITLE
Breaking change in 2.0.2 - karafka.publish to karafka.produce

### ISSUE THREAD

**Issue by whithajess** [karafka/karafka-testing#96]
I can see this in the `2.0.2` patch notes:
```
Rename `karafka.publish` to `karafka.produce` to align naming conventions.
```
But it doesn't call it out as a **breaking change** and probably shouldn't be in a patch release. 

Even though it's a testing library the change broke all of our tests - probably worth noting in the `CHANGELOG.md` as its a public method.

**Comment by mensfeld** [comment]
> probably shouldn't be in a patch release.

I do not follow semantic versioning as I want it to be aligned with major karafka version (2.0 => 2.0) but I should have released 2.0.1.1.
